name: Build DMX Portal
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Installing .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
        include-prerelease: true
    - name: Restoring packages
      run: dotnet restore
    - name: Building Project(s)
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
