name: Provision DMX Portal
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AzureTenantId: ${{ secrets.AZURE_TENANT_ID }}
      AzureAdAppProvisionClientId: ${{ secrets.AZURE_AD_APP_PROVISION_CLIENT_ID }}
      AzureAdAppProvisionClientSecret: ${{ secrets.AZURE_AD_APP_PROVISION_CLIENT_SECRET }}
      AzureAdAppDmxPortalClientId: ${{ secrets.AZURE_AD_DMX_PORTAL_CLIENT_ID }}
      AzureAdAppDmxPortalClientSecret: ${{ secrets.AZURE_AD_DMX_PORTAL_CLIENT_SECRET }}
      AzureAdDmxPortalInstance: ${{ secrets.AZURE_AD_DMX_PORTAL_INSTANCE }}
      AzureAdDmxPortalDomain: ${{ secrets.AZURE_AD_DMX_PORTAL_DOMAIN }}
      AzureAdDmxPortalCallbackPath: ${{ secrets.AZURE_AD_DMX_PORTAL_CALLBACKPATH }}
      AzureAdDmxGatekeeperAppIdUri: ${{ secrets.AZURE_AD_DMX_GATEKEEPER_APP_ID_URI }}
      AzureAdAppDmxGatekeeperScopesGetAllLabs: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_SCOPES_GETALLLABS }}
      AzureAdAppDmxGatekeeperScopesPostLab: ${{ secrets.AZURE_ADAPP_DMXGATEKEEPER_SCOPES_POSTLAB }}
      AzureAppServiceDmxGatekeeperApiUrl: ${{ secrets.AZURE_APP_SERVICE_DMX_GATEKEEPER_API_URL }}
      AzureAppServiceDmxGatekeeperApiAccessKey: ${{ secrets.AZURE_APP_SERVICE_DMX_GATEKEEPER_API_ACCESS_KEY }}
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.101
        include-prerelease: false
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\DMX.Portal.Web.Infrastructure.Provision\DMX.Portal.Web.Infrastructure.Provision.csproj
